services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - "ollama_models:/root/.ollama"
    # post_start:
    #   - command: ollama pull xxx
    networks:
      - intnet
      
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.1
    restart: unless-stopped
    env_file: ../.env
    networks:
      - intnet
    ports:
      - "127.0.0.1:9200:9200"
    deploy:
      resources:
        limits:
          memory: 1G
      
  pgdb:
    container_name: pgdb
    image: magicdocu/postgres
    restart: unless-stopped
    volumes: 
      - "pgsql_db:/var/lib/postgresql/"
    ports:
      - "127.0.0.1:5432:5432"
    env_file: ../.env
    networks:
      - intnet 
      
  redis:
    container_name: redis
    image: redis:8.6.1-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - intnet

volumes:
  ollama_models:
  pgsql_db:
  redis-data:

networks:
  intnet:
    external: false
