services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - "ollama_models:/root/.ollama"
    post_start:
      - command: ollama pull nomic-embed-text:v1.5
      - command: ollama pull llama3.2:1b
    networks:
      - intnet

  pgdb:
    container_name: pgdb
    image: magicdocu/postgres
    restart: unless-stopped
    volumes: 
      - "pgsql_db:/var/lib/postgresql/"
    ports:
      - "127.0.0.1:5432:5432"
    env_file: ../.env
    networks:
      - intnet 
      
  redis:
    container_name: redis
    image: redis:8.6.1-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - intnet
      
  magicdocu:
    container_name: magicdocu
    image: magicdocu/django
    restart: unless-stopped
    volumes:
      - "django_uploads:/uploads"
      - "./config:/config"
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - intnet
    depends_on:
      pgdb:
        condition: service_healthy
      ollama:
        condition: service_started

volumes:
  ollama_models:
  pgsql_db:
  redis-data:
  django_uploads:

networks:
  intnet:
    external: false
