# Generated by Django 6.0.2 on 2026-02-28 16:20

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_documentkeywords_documentkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentkeyword',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(related_name='documents', to='core.keyword'),
        ),
        migrations.DeleteModel(
            name='DocumentHistory',
        ),
        migrations.DeleteModel(
            name='DocumentKeyword',
        ),
    ]
