# Generated by Django 6.0.2 on 2026-02-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_documentchunk_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summarised',
            field=models.BooleanField(default=False),
        ),
    ]
